### ISSUE TITLE
Bug : Searching bulb doesn't find lightbulb-group

### ISSUE THREAD

**Issue by julienreszka** [PeterShaggyNoble/MDI-Sandbox#21]
Given I'm on the website [https://petershaggynoble.github.io/MDI-Sandbox/](https://petershaggynoble.github.io/MDI-Sandbox/)
When I search for `bulb`
Then I should see 22 results with `lightbulb-group` among them
Unexpectedly I see 4 results Instead

**Comment by PeterShaggyNoble** [comment]
Thanks, @julienreszka.

I've added the alias `bulb` to all the `lightbulb` icons in the main project and will push an update here shortly.

Note that this is just a side-project of [Material Design Icons](https://materialdesignicons.com/) that isn't *directly* affiliated with it - if you spot anything like this in the future or, indeed, would like to request the addition of new icons, you can do so in [the main MDI repo](https://github.com/Templarian/MaterialDesign/).
