### ISSUE TITLE
Download Vector Drawable exports faulty XML

### ISSUE THREAD

**Issue by johannroux** [PeterShaggyNoble/MDI-Sandbox#23]
Hi! Thank you so much for your website, I'm in love with it.
I noticed that the Download Vector Drawable button on the right exports faulty XML, such as:

```
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:height="24dp" android:width="24dp" android:viewportWidth="24" android:viewportHeight="24"><path android:fillColor="
```

Would it be possible to fix it?

I'd also suggest giving an Android-Studio-friendly name, by replacing the dashes with underscores.

**Comment by PeterShaggyNoble** [comment]
Thanks for bringing this to my attention, @johannroux. I have both of those fixed for the next update, which I'll be pushing within the hour.

I don't use vector drawables myself so, if you have any other issues with or feedback about them, please do let me know.
